<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>afc</string>
	</array>
	<key>name</key>
	<string>Tubaina Afc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#listTag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#refTag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockTags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inlineTags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#noteTag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockTags</key>
		<dict>
			<key>begin</key>
			<string>(\[)(chapter|section|list|box|code|title)(.*?)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.italic.description.afc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\[)(\/)(chapter|section|list|box|code|title)(\])</string>
			<key>name</key>
			<string>entity.name.tag.container.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inlineSyntaxes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+)?(\*)^(\*)</string>
					<key>name</key>
					<string>markup.italic.item.afc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.content.afc</string>
				</dict>
			</array>
		</dict>
		<key>inlineSyntaxes</key>
		<dict>
			<key>begin</key>
			<string>(\*|_|%|:){2}</string>
			<key>end</key>
			<string>(\*|_|%|:){2}</string>
			<key>name</key>
			<string>markup.bold.inline.afc</string>
		</dict>
		<key>inlineTags</key>
		<dict>
			<key>begin</key>
			<string>(\[)(quote|index|TODO|img|label)</string>
			<key>end</key>
			<string>(\])</string>
			<key>name</key>
			<string>entity.name.tag.inline.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.w.afc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.w.afc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(.*?)(w=|h=)([0-9]+%?)</string>
					<key>name</key>
					<string>markup.italic.images.afc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.italic.content.afc</string>
				</dict>
			</array>
		</dict>
		<key>noteTag</key>
		<dict>
			<key>begin</key>
			<string>(\[)(note)(.*?)(\])</string>
			<key>end</key>
			<string>(\[)(\/)(note)(\])</string>
			<key>name</key>
			<string>comment.inline.tag.note.afc</string>
		</dict>
		<key>refTag</key>
		<dict>
			<key>begin</key>
			<string>(\[)(ref)(-code|-label)?(\s)</string>
			<key>end</key>
			<string>(\])</string>
			<key>name</key>
			<string>entity.name.tag.ref.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>_</string>
					<key>name</key>
					<string>invalid.illegal.underscore.afc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.inline.tag.ref.afc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.afc</string>
	<key>uuid</key>
	<string>cb37ad00-724d-4914-806f-ba7d56e60ccc</string>
</dict>
</plist>
